version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-airbnb-typescript
    versions:
    - "> 6.3.2"
  - dependency-name: "@types/jest"
    versions:
    - "> 24.9.1"
  - dependency-name: "@types/jest"
    versions:
    - ">= 25.a, < 26"
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.42"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: eslint
    versions:
    - 7.11.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: ts-jest
    versions:
    - 26.4.1
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: jest
    versions:
    - 26.6.0
